### ISSUE TITLE
 fatal error LNK1106: invalid file or disk full: cannot seek to 0x1E696A [C:\Users\Administrator\Desktop\orbit-electron\node_modules\sha3\build\sha3.vcxproj]

### ISSUE THREAD

**Issue by qazujmko** [phusion/node-sha3#31] opened 2018-04-05 04:19 UTC
fatal error LNK1106: invalid file or disk full: cannot seek to 0x1E696A [C:\Users\Administrator\Desktop\orbit-electron\node_modules\sha3\build\sha3.vcxproj]
...
..\src\addon.cpp(49): warning C4316: 'SHA3Hash': object allocated on the heap may not be aligned 32 [C:\Users
\Administrator\Desktop\orbit-electron\node_modules\sha3\build\sha3.vcxproj]
..\src\addon.cpp(59): warning C4996: 'v8::Function::NewInstance': was declared deprecated [C:\Users\Administr
ator\Desktop\orbit-electron\node_modules\sha3\build\sha3.vcxproj]
  c:\users\administrator\.node-gyp\9.9.0\include\node\v8.h(3894): note: see declaration of 'v8::Function::New
  Instance'
C:\Users\Administrator\.node-gyp\9.9.0\x64\node.lib : fatal error LNK1106: invalid file or disk full: cannot
seek to 0x1E696A [C:\Users\Administrator\Desktop\orbit-electron\node_modules\sha3\build\sha3.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\
build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:180:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_mod
ules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\Desktop\orbit-electron\node_modules\sha3
gyp ERR! node -v v9.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sha3@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-04-05T04_18_42_330Z-debug.log

**Comment by canterberry** [comment] 2018-04-30 02:52
@qazujmko I've created #37 to investigate potential improvements to the installation process for this library. Were you able to work around your issue?

Also, v1.2.1 was published earlier today, which modernizes some of the dependency packages. While this release doesn't contain a direct fix for this issue, it's possible that it may have indirectly had an impact.

**Comment by canterberry** [comment] 2018-10-26 20:28
Closing as a duplicate of #37, which covers all issues related to install-time compilation steps.

**Closed by canterberry** 2018-10-26 20:28 UTC
Labels: duplicate
