### ISSUE TITLE
Support the actual SHA3 (non keccak) hashing algorithm 

### ISSUE THREAD

**Issue by miguelmota** [phusion/node-sha3#43] opened 2018-10-26 20:05 UTC
This library doesn't produce the expected results of SHA3 https://emn178.github.io/online-tools/sha3_256.html

```js
const SHA3 = require('sha3');

d = new SHA3.SHA3Hash(256);
d.update('a');
console.log(d.digest('hex'))
// 3ac225168df54212a25c1c01fd35bebfea408fdac2e31ddd6f80a4bbf9a5f1cb
```

Expected

```
80084bf2fba02475726feb2cab2d8215eab14bc6bdd8bfb2c8151257032ecd8b
```

**Comment by canterberry** [comment] 2018-10-26 20:15
Yeah, this is a known issue, and a duplicate of #36. This library in its current state is a bit unwieldy to maintain, so there's been talk of (carefully) rewriting it in native JavaScript.

**Closed by canterberry** 2018-10-26 20:15 UTC
