### ISSUE TITLE
Any chance we can get a 1.2.3 release that builds on node 12?

### ISSUE THREAD

**Issue by davidmurdoch** [phusion/node-sha3#50] opened 2019-04-30 23:09 UTC
https://github.com/phusion/node-sha3/pull/44#issuecomment-437689120 shows that the native implementation is about 45x faster than the latest pure-JS version. For those of us that don't mind the build complications keeping the 1.2.3 branch updated would be much appreciated!

**Comment by canterberry** [comment] 2019-04-30 23:46
In #44 I mentioned that the 2.x branch makes a tradeoff between readability and performance. During that research I did come across some techniques (from studying the js-sha3 pure JavaScript implementation) that led to significant performance gains. I ended up not keeping that work because I wasn't happy with the quality of my implementation, but it's something I've been meaning to come back to.

The benchmarks show that near-native speeds are possible, as evidenced by the metrics for the js-sha3 library. Loop unrolling, alone, resulted in some significant performance gains, so before considering reverting back to 1.x, I'd propose a round of performance improvements to 2.x. Maybe we can have our cake (:cake: performance) and eat it, too (:fork_and_knife: no build complications).

**Comment by canterberry** [comment] 2019-05-02 06:48
#53 mitigates, to some extent, performance concerns. A 75% reduction in computation time translates to this library only being ~11x slower than a native implementation (vs 45x), which is much closer to the ballpark of acceptable tradeoffs for having a pure JavaScript implementation.

**Comment by canterberry** [comment] 2019-05-02 20:57
@davidmurdoch v2.0.2 has now been released with the performance improvements and formal support for Node.js 12.x. If this addresses your concerns underlying the request to maintain v1.x, feel free to close this issue. There are further opportunities to optimize, but v2.0.2 narrows the gap in the short term. For applications that are highly performance-sensitive, I'd still recommend js-sha3 or a library with bindings to a native C implementation.

**Comment by canterberry** [comment] 2019-05-08 21:49
Resolved in #55, which addresses `node-gyp` compilation issues caused by Node.js native API drift+deprecation+removal.

**Comment by canterberry** [comment] 2019-05-08 22:15
v1.2.3 has been published, which should address Node.js 12.x compatibility issues. Please give it a shot and let me know if you run into any issues.

**Closed** 2019-05-08 22:15 UTC
